
import streamlit as st
from streamlit_tile import streamlit_tile
import pandas as pd
from components.FileHandler import DataManager
from components.dataanalysis import DataAnalyis

class OverviewPage:
    def __init__(self, config):
        self.config = config
        self.data_manager = DataManager(config)
        self.map = self.config.get('datadetails', {})
        self.forecast_horizon = self.map.get('forecast_horizon','13')
  

    def show(self, forecast_file, simulation_file):
        
        """Main entry point to render the page"""
        st.markdown('<h1 class="custom-h1">Forecast Overview</h1>', unsafe_allow_html=True)
        # st.caption('Year-to-Date Performance')
        try:
            df = self.data_manager.get_dataframe(forecast_file)
            analysis = DataAnalyis(df, self.config)
            
            # This will trigger the ValueError if format is wrong
            enriched_df = analysis.prepare_data()
            
            summary = analysis.get_ytd_comparison(enriched_df)
            print(summary)
      
            # 1. Get dynamic naming from config
            obj = self.config['datadetails']['objective']
            
            # 2. Extract values from summary (using the keys generated by DataAnalysis)
            # Note: Make sure these keys match exactly what your class returns!
            curr_actual = summary.get(f'Current_YTD_Actual_{obj}', 0)
            last_actual = summary.get(f'Last_Year_YTD_Actual_{obj}', 0)
            curr_year = summary.get(f'Current_Year', 0)
            last_year = summary.get(f'Last_Year', 0)
            Curr_week = summary.get(f'Current_Week', 0)
            accuracy_ytd = summary.get(f'Current_YTD_Forecast_Accuracy_{obj}', 0)

            st.markdown('<h2 class="custom-h2">' + str(self.forecast_horizon) + ' week forward view (Week ' + str(Curr_week) + ' - FY' + str(last_year) + ' to  FY' + str(curr_year) + ') </h2>', unsafe_allow_html=True)

            # 3. Calculate YoY % Change
            yoy_change = ((curr_actual - last_actual) / last_actual * 100) if last_actual != 0 else 0
            
            growth_icon = "trending_up" if yoy_change >= 0 else "trending_down"
            growth_color = "green" if yoy_change >= 0 else "red"

            # --- ROW 1: Metric Tiles (Small & Compact) ---
            # We use a container to keep them grouped
            with st.container(horizontal=True):
                
                t1, t2, t3, t4 = st.columns(4)
                
                with t1:
                    
                    users_clicked=streamlit_tile(title=f"TY YTD Forecast", 
                                   description=f"{curr_actual:,.0f}", 
                                   icon="payments",
                                #    show_button=False,
                                   height=200,
                                    # width=900,
                                    key="green_tile_1")
                with t2:
                   reports_clicked=settings_clicked= streamlit_tile(title=f"Last Year {obj} YTD",
                                    description=f"{last_actual:,.0f}",
                                     icon="history", color_theme="indigo",
                                     height=200,
                                     width=900,
                                     key="green_tile_2")
                with t3:
                    streamlit_tile(title="YoY Growth", 
                                   description=f"{yoy_change:+.1f}%", 
                                   icon="trending_up", 
                                   color_theme="green",
                                   height=200,
                                    width=900,
                                    key="green_tile_3")
                with t4:
                    streamlit_tile(title="YTD Forecast Accuracy", 
                                   description=f"{accuracy_ytd:.1f}%", 
                                   icon="trending_up", 
                                   color_theme="green",
                                   height=200,
                                   width=900,
                                   key="green_tile_4")

                # Handle tile clicks
                    if users_clicked:
                        st.info("Users section accessed!")
                    if settings_clicked:
                        st.info("Settings section accessed!")
                    if reports_clicked:
                        st.info("Reports section accessed!")

            # --- ROW 2: The Main Feature (Big Graph) ---
            with st.container(border=True):
                st.markdown("### 📈 Revenue vs Forecast Trend")
                # Using container width makes it stretch to fill the blue box in your diagram
                st.line_chart(df, x=analysis.date_col, y=[analysis.actual_col, analysis.target_col], use_container_width=True)

            # --- ROW 3: Data Details (Table and Distribution) ---
            col_left, col_right = st.columns([1.5, 1]) # Left side is slightly wider for the table

            with col_left:
                with st.container(border=True):
                    st.markdown("### 📋 Store Performance Detail")
                    # height=300 keeps the table from becoming too long
                    st.dataframe(df.head(20), use_container_width=True, height=300)

            with col_right:
                with st.container(border=True):
                    st.markdown("### 🎯 Accuracy by Category")
                    # A bar chart or pie chart fits well in the smaller right box
                    st.bar_chart(df.groupby('SKU')[analysis.actual_col].sum(), use_container_width=True, height=300)
        except ValueError as e:
            # Show the "Please correct your format" message
            st.error(str(e))
            st.info("💡 Tip: Open your CSV in Notepad to ensure the date is strictly MM-DD-YYYY. "
                    "Excel often changes formats automatically.")
            st.stop() # Prevents the rest of the page from trying to load


        # # Call the horizontal line - it will automatically use your 'hr' CSS
        # # st.markdown('<hr>', unsafe_allow_html=True)
        # # st.divider()

        # # # Handle case where no files are uploaded yet
        # # if not forecast_file:
        # #     st.warning("Please upload a Forecast File in the sidebar to begin.")
        # #     return
# 
        # # # 1. Use DataManager to load the data
        # # # DataManager should handle things like pd.read_csv() and caching
        # df_forecast = self.data_manager.get_dataframe(forecast_file)
        # data_analyzer = DataAnalyis(df_forecast, self.config)

        # # # 2. Middle Section: Graph
        # # with st.container():
        # #     st.subheader("Performance Over Time")
        # #     # Example plotting using the loaded dataframe
        # #     if 'date' in df_forecast.columns and 'value' in df_forecast.columns:
        # #         st.line_chart(df_forecast.set_index('date')['value'])
        # #     else:
        # #         st.info("Upload data with 'date' and 'value' columns to see the chart.")

        # # # 3. Bottom Section: Two Tables
        # # st.subheader("Data Breakdowns")
        # # col1, col2 = st.columns(2)

        # # with col1:
        # #     st.write("### Head (Preview)")
        # #     st.dataframe(df_forecast.head(), width="stretch")

        # # with col2:
        # #     st.write("### Tail (Summary)")
        # #     st.dataframe(df_forecast.tail(5), width="stretch")
